[build]
  publish = "dist"
  command = "yarn generate"

[context.develop]
  command = "yarn generate:noindex"

[context.deploy-preview]
  command = "yarn generate:noindex"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = false
