name: Build

on:
  push:
    branches:
    - master
    paths:
    - packages/app/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Install dependencies
      run: yarn --frozen-lockfile
      working-directory: ./packages/app

    - name: Build
      run: yarn build
      working-directory: ./packages/app
      env:
        GA_ID: ${{ secrets.GA_ID }}

    - name: Remove .gitignore
      run: rm .gitignore
      working-directory: ./packages/app

    - name: Copy .gitignore
      run: cp .gitignore.workflow .gitignore
      working-directory: ./packages/app

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./packages/app
        publish_branch: build
